### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by 4enetic0** [deepimagination/PoE-GAN#16]
imaginaire.cc/gaugan2/ 

http://gaugan.org/gaugan2/

on both sides unfortunately nothing works as it should I get no image in the output until the day before yesterday everything has still worked

![Unbenannt](https://user-images.githubusercontent.com/111881064/186164371-bd28068d-3058-4529-8704-617061ce45ad.png)

**Comment by houseofc** [comment]
I get the same aws server address, maybe it's that server? IIRC it is supposed to grab one of a bunch.
