### ISSUE TITLE
WHY DOES GANGAN2 DO NOTHING?

### ISSUE THREAD

**Issue by impzdpwer112** [deepimagination/PoE-GAN#27]
**WHY IT DOES  _NOTHING!_** <sup>PLEASE HELP </sup>
FIX IT!!

**Comment by Xinned** [comment]
SAME HERE FIX IT!!!!

**Comment by pomello03** [comment]
Exactly, it doesn't. Do i need a specific hardware like for NVIDIA Canvas?

**Comment by JustAlex24** [comment]
As far as I know, for Nvidia Canvas you need RTX GPU for it to work.

**Comment by 4enetic0** [comment]
hell nah wont upgrade my 1080 until its dead

**Comment by plaraje** [comment]
same, it doesnt render anything

**Comment by FrostedBagel1** [comment]
it is an issue on their end its not a hardware issue because i used to use this all the time and it worked up until recently when it stopped giving results.

**Comment by plaraje** [comment]
they told me to turn off vpn and try

**Comment by plaraje** [comment]
> they told me to turn off vpn and try

nais work

**Comment by impzdpwer112** [comment]
long











































































wow
